export enum EncounterCommandType {
	PLAYER_UPDATE = 'PLAYER_UPDATE',
	ADD_PLAYER = 'ADD_PLAYER',
	REMOVE_PLAYER = 'REMOVE_PLAYER',
	LIGHT_SOURCE = 'LIGHT_SOURCE',
	ADD_NOTATION = 'ADD_NOTATION',
	NOTATION_UPDATE = 'NOTATION_UPDATE',
	REMOVE_NOTATION = 'REMOVE_NOTATION',
	EPHEMERAL_NOTATION = 'EPHEMERAL_NOTATION',
	WALL_CHANGE = 'WALL_CHANGE',
}
