
export enum MqMessageType {
	ENCOUNTER = 'ENCOUNTER',
	FRIEND_REQUEST = 'FRIEND_REQUEST',
	FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
	CAMPAIGN_INVITE = 'CAMPAIGN_INVITE',
	CAMPAIGN_UPDATE = 'CAMPAIGN_UPDATE',
	CHAT = 'CHAT',
}