export enum CellRegion {
  CORNER = 'CORNER',
  CENTER = 'CENTER',

  TOP_EDGE = 'TOP_EDGE',
  LEFT_EDGE = 'LEFT_EDGE',
  FWRD_EDGE = 'FORWARD',
  BKWD_EDGE = 'BACKWARD',

  TOP_QUAD = 'TOP_QUAD',
  BOTTOM_QUAD = 'BOTTOM_QUAD',
  LEFT_QUAD = 'LEFT_QUAD',
  RIGHT_QUAD = 'RIGHT_QUAD'
}
